### ISSUE TITLE
make event de/serialization more obvious

### ISSUE THREAD

**Issue by kra** [futel/s3-event-writer#2]
this is currently where events are turned into the eventual s3 serialization, right? If the fields were more obvious it would help coordinate the sanitation of the events on the other end, let us understand it quicker, etc.

Doesn't have to be fancy but we could start with a module level map method or clear map structure?

https://github.com/futel/s3-event-writer/blob/main/src/msg_mapper.py

**Comment by breedx2** [comment]
The `msg_mapper.py` that you linked to is responsible for converting the raw SQS response body json into an intermediate format. Yes, the intermediate format is what eventually gets serialized to s3. There are 3 extra fields in this intermediate format (which I think is [relatively clear here](https://github.com/futel/s3-event-writer/blob/5a9c60c4110163f64b2c83d774925e223ba3186d/src/msg_mapper.py#L30):
* `id` - not used, we could drop it
* `hostname` - needed because we [use it later for filtering](https://github.com/futel/s3-event-writer/blob/5a9c60c4110163f64b2c83d774925e223ba3186d/src/sqs_buffer.py#L14)
* `receipt_handle` - required to perform the delete from sqs after we are done with an event

I also think [the current final output mapping](https://github.com/futel/s3-event-writer/blob/487ff9bd273e9923585ca65e40af8a49b45e0fc8/src/msg_mapper.py#L15) is pretty easy to follow, but maybe there are some ways to make this all more pythonic and easier to read/maintain.

Maybe just having these links and a block in the readme would help? If not, submit a PR and we'll chat.

**Comment by kra** [comment]
ok so map_final describes the output format:

https://github.com/futel/s3-event-writer/blob/487ff9bd273e9923585ca65e40af8a49b45e0fc8/src/msg_mapper.py#L15

and _convert_msg describes the input format:

https://github.com/futel/s3-event-writer/blob/487ff9bd273e9923585ca65e40af8a49b45e0fc8/src/msg_mapper.py#L22

correct?

**Comment by breedx2** [comment]
Yeah, with the caveat that `_convert_msg` doesn't fully describe the input -- just the parts we care about.

**Comment by breedx2** [comment]
Reopen if more info needed or something else specific.
